export const productTableData = [
    {
        id: 100,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 1",
        visibilitas: true,
        kategori: "Sekali Pertemuan",
        harga: 100000,
    },
    {
        id: 2,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 2",
        visibilitas: true,
        kategori: "Sekali Pertemuan",
        harga: 200000,
    },
    {
        id: 3,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 3",
        visibilitas: true,
        kategori: "Sekali Pertemuan",
        harga: 300000,
    },
    {
        id: 4,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 4",
        visibilitas: true,
        kategori: "Sekali Pertemuan",
        harga: 400000,
    },
    {
        id: 5,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 5",
        visibilitas: true,
        kategori: "Sekali Pertemuan",
        harga: 500000,
    },
    {
        id: 6,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 6",
        visibilitas: true,
        kategori: "Paket Bimbingan",
        harga: 600000,
    },
    {
        id: 7,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 7",
        visibilitas: true,
        kategori: "Paket Bimbingan",
        harga: 700000,
    },
    {
        id: 8,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 8",
        visibilitas: true,
        kategori: "Paket Bimbingan",
        harga: 800000,
    },
    {
        id: 9,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 9",
        visibilitas: true,
        kategori: "Paket Bimbingan",
        harga: 900000,
    },
    {
        id: 10,
        gambar: "https://via.placeholder.com/150",
        nama: "Product 10",
        visibilitas: true,
        kategori: "Paket Bimbingan",
        harga: 1000000,
    },
];
